Repository plar/go-adaptive-radix-tree, pull requests merged in 2024-12, with the labels that each got.

#33 Reverse iteration feature
  README.md
  api.go
  node_16.go
  node_256.go
  node_4.go
  node_48.go
  node_ref.go
  tree.go
  tree_iterator.go
  tree_test.go
  tree_traversal.go
  tree_traversal_test.go
  utils.go
  utils_test.go
Labels: feature

#39 docs: clarify lexicographical ordering in key sorting behavior
  README.md
Labels: documentation

#40 fix: module path should reflect v2 release
  README.md
  doc.go
  examples/gtree/gtree.go
  examples/gtree/main.go
  examples/tree.go
  go.mod
Labels: chore

#48 docs: add migration section
  README.md
Labels: documentation
